name: Go Test

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.0

      - name: Install dependencies
        run: go mod download

      - name: Test
        run: go test ./...
